apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - gateway-message-service/k8s/message-service.yaml
  - gateway-billboard-client/k8s/billboard-client.yaml
  - webflux-gateway/k8s/gateway-server.yaml

